### ISSUE TITLE
Error: Cannot find module `'./src/plugins/editing/package.json'`

### ISSUE THREAD

**Issue by mohammed21986** [g3w-suite/g3w-client#638]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

```
 npm run watch:plugins
```

> g3w-client@3.9.8 watch:plugins
> npm run dev
>
>
> g3w-client@3.9.8 dev
> gulp dev
>
> [G3W-CLIENT] environment: development
> [G3W-CLIENT] output folder: /data/g3w-suite-docker/config/g3w-suite/overrides
> node:internal/modules/cjs/loader:1031
>   throw err;
>   ^
>
> Error: Cannot find module './src/plugins/editing/package.json'
> Require stack:
> - /data/g3w-client/gulpfile.js
> - /data/g3w-client/node_modules/gulp/bin/gulp.js
>      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
>      at Function.resolve (node:internal/modules/cjs/helpers:125:19)
>      at get_version (/data/g3w-client/gulpfile.js:94:32)
>      at /data/g3w-client/gulpfile.js:67:122
>      at Array.map (<anonymous>)
>      at setNODE_ENV (/data/g3w-client/gulpfile.js:67:64)
>      at Object.<anonymous> (/data/g3w-client/gulpfile.js:164:1)
>      at Module._compile (node:internal/modules/cjs/loader:1198:14)
>      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
>      at Module.load (node:internal/modules/cjs/loader:1076:32) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/data/g3w-client/gulpfile.js',
>     '/data/g3w-client/node_modules/gulp/bin/gulp.js'
>   ]
> }

### Steps to reproduce

Have followed the document availaible on git.

### Environment

- g3w-admin: 3.7
- g3w-client: 3.9
- browser: Chrome
- operating system: Ubuntu 20

**Comment by Raruto** [comment]
Hi @mohammed21986,

what do you see in this directory?

```
/data/g3w-client/plugins/editing/
```

👋 Raruto

**Comment by mohammed21986** [comment]
> Hi @mohammed21986,
> 
> what do you see in this directory?
> 
> ```
> /data/g3w-client/plugins/editing/
> ```
> 
> 👋 Raruto

Hi @Raruto, inside plugins there is no directory, while i'm trying to run npm run dev then it's throwing below error only.

```
Error: Cannot find module './src/plugins/editing/package.json'
```

i can see there is path inside the `config.js` but it's only `./src/plugins` the remaining getting added automatically.

**Comment by mohammed21986** [comment]
```
root@ip-XX-XX-XX-XX:/data/g3w-client# npm run dev
```

```log

g3w-client@3.9.8 dev
gulp dev

[G3W-CLIENT] environment: development
[G3W-CLIENT] output folder: ../g3w-suite-docker/config/g3w-suite/overrides
node:internal/modules/cjs/loader:1031
  throw err;
  ^

Error: Cannot find module './src/plugins/editing/package.json'
Require stack:
- /data/g3w-client/gulpfile.js
- /data/g3w-client/node_modules/gulp/bin/gulp.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.resolve (node:internal/modules/cjs/helpers:125:19)
    at get_version (/data/g3w-client/gulpfile.js:94:32)
    at /data/g3w-client/gulpfile.js:67:122
    at Array.map (<anonymous>)
    at setNODE_ENV (/data/g3w-client/gulpfile.js:67:64)
    at Object.<anonymous> (/data/g3w-client/gulpfile.js:164:1)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/g3w-client/gulpfile.js',
    '/data/g3w-client/node_modules/gulp/bin/gulp.js'
  ]
}
```

```
root@ip-XX-XX-XX-XX:/data/g3w-client# cat config.js
```

```js
const { version }      = require('./package.json');

const G3W_HOST_SCHEMA  = 'http';
const G3W_HOST         = '127.0.0.1'; // local development server
const G3W_ADMIN_PORT   = '8000';      // G3W-ADMIN development server
const G3W_CLIENT_PORT  = '3000';      // G3W-CLIENT development server

const G3W_PLUGINS = [                 // override "initConfig->group->plugins" attribute for custom plugin development
  // "your-plugin-folder-name-1",
  // "your-plugin-folder-name-2",
  // "your-plugin-folder-name-3",
];

const G3W_KEYS = {
  // google: '<INSERT HERE YOUR GOOGLE API KEY>',
  // bing: '<INSERT HERE YOUR BING API KEY>'
};

const G3W_IFRAME = {                  // testing MESSAGE sent to "Open in iframe" map control
  id: null,
  action: 'app:getcenter',            // or 'app:getextent'
  data: { epsg: 4326 }
};

let conf = {
  assetsFolder:  './src/assets',                                            // path to G3W-CLIENT assets folder
  pluginsFolder: './src/plugins',                                           // path to G3W-CLIENT plugins folder
  admin_plugins_folder:   '../g3w-admin/g3w-admin',                         // path to G3W-ADMIN plugins folder
  admin_overrides_folder: '../g3w-suite-docker/config/g3w-suite/overrides', // path to G3W-SUITE overrides folder
  host: G3W_HOST,
  port: G3W_CLIENT_PORT,
  // proxy configuration for local G3W_ADMIN server (where G3W-ADMIN is running)
  proxy: {
    host: G3W_HOST,
    url: `${G3W_HOST_SCHEMA}://${G3W_HOST}:${G3W_ADMIN_PORT}/`,
  },
  test: {
    path: '/test/config/groups/'
  },
  plugins: G3W_PLUGINS,
  keys: G3W_KEYS,
  devConfig() {
    g3wsdk.core.ApplicationService.once('ready', () => { });
    g3wsdk.core.ApplicationService.once('initconfig', () => {
      initConfig.group.vendorkeys = Object.assign(initConfig.group.vendorkeys || {}, G3W_KEYS);
      initConfig.group.plugins    = Object.assign(initConfig.group.plugins || {}, G3W_PLUGINS.reduce((a, v) => ({ ...a, [v]: { ...initConfig.group.plugins[v], gid: initConfig.group.initproject, baseUrl: initConfig.staticurl }}), {}));
    });
    g3wsdk.gui.GUI.once('iframe:message', (w, e) => { w.postMessage(G3W_IFRAME, '*') });
    g3wsdk.gui.GUI.once('ready', () => { console.log('ready'); });
  }
};

// backward compatibilities (v3.x)
if (version < '4') {
  conf.assetsFolder           = (version.localeCompare('3.7.0', undefined, { numeric: true, sensitivity: 'case' }) < 0 ? './assets' : conf.assetsFolder);
  conf.distFolder             = './dist';
  conf.clientFolder           = './dist/client';
  conf.admin_static_folder    = `${conf.admin_plugins_folder}/client/static`;
  conf.admin_templates_folder = `${conf.admin_plugins_folder}/client/templates`;
  conf.createProject          = { before() {}, after() {} };
  conf.setCurrentProject      = { before() {}, after() {} };
  conf.plugins                = conf.plugins.reduce((a, v) => ({ ...a, [v]: { gid: 'qdjango:1', baseurl: `.${conf.distFolder}` }}), {});
  conf.proxy.routes           = ['/media', '/api', '/ows', '/static', '/en/', '/it/', '/upload/'];
  conf.proxy.urls             = conf.proxy.routes;
  conf.localServerPort        = conf.port;
  conf.g3w_admin_paths        = {
    dev: {
      g3w_admin_plugins_basepath:     conf.admin_plugins_folder.replace(/\/?$/, '/'),
      g3w_admin_client_dest_static:   conf.admin_static_folder,
      g3w_admin_client_dest_template: conf.admin_templates_folder
    }
  };
}

module.exports = conf;
```

```
root@ip-XX-XX-XX-XX:/data/g3w-client# ls -lrtha /data/
```

```log
total 40K
drwx------  2 root root  16K Apr 23 17:29 lost+found
drwxr-xr-x 18 root root 4.0K Jun  3 08:04 g3w-admin
drwxr-xr-x  9 root root 4.0K Jun  3 11:01 g3w-suite-docker
drwxr-xr-x 20 root root 4.0K Jun  3 12:40 ..
drwxr-xr-x  5 root root 4.0K Jun  3 12:40 g3w-suite-docker-dev
drwxr-xr-x  7 root root 4.0K Jun  3 13:01 .
drwxr-xr-x  7 root root 4.0K Jun  3 13:35 g3w-client
```

**Comment by Raruto** [comment]
> there is no directory: `./src/plugins`

Your gulpfile should clone/check for these default repositories (perhaps some issue with relative paths?):

https://github.com/g3w-suite/g3w-client/blob/8f2e89f0029ee6f306c624997dc2c72a97a1d339/gulpfile.js#L354-L372

https://github.com/g3w-suite/g3w-client/blob/8f2e89f0029ee6f306c624997dc2c72a97a1d339/gulpfile.js#L496-L511

At worst, try to clone them manually before running: `npm run dev`

**Comment by mohammed21986** [comment]
root@ip-XX-XX-XX-XX:/data/g3w-client# npm run dev

> g3w-client@3.9.8 dev
> gulp dev

[G3W-CLIENT] environment: development
[G3W-CLIENT] output folder: ../g3w-suite-docker/config/g3w-suite/overrides

[11:24:25] Using gulpfile /data/g3w-client/gulpfile.js
[11:24:25] Starting 'dev'...
[11:24:25] Starting 'clean:overrides'...
[11:24:25] Finished 'clean:overrides' after 2.87 ms
[11:24:25] Starting 'clone:default_plugins'...


### Cloning default plugins ###

Cloning into './src/plugins/editing'...
remote: Enumerating objects: 10591, done.
remote: Counting objects: 100% (2197/2197), done.
remote: Compressing objects: 100% (725/725), done.
remote: Total 10591 (delta 1510), reused 1895 (delta 1416), pack-reused 8394
Receiving objects: 100% (10591/10591), 2.39 MiB | 3.74 MiB/s, done.
Resolving deltas: 100% (7302/7302), done.
[11:24:27] No gulpfile found
[11:24:27] 'clone:default_plugins' errored after 1.77 s
[11:24:27] Error: Command failed: gulp --gulpfile ./src/plugins/editing/gulpfile.js default
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Gulp.<anonymous> (/data/g3w-client/gulpfile.js:369:7)
    at module.exports (/data/g3w-client/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/data/g3w-client/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/data/g3w-client/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/data/g3w-client/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/data/g3w-client/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/data/g3w-client/node_modules/run-sequence/index.js:75:5)
[11:24:27] 'dev' errored after 1.77 s
[11:24:27] Error in plugin 'run-sequence(clone:default_plugins)'
Message:
    Command failed: gulp --gulpfile ./src/plugins/editing/gulpfile.js default
Details:
    status: 1
    signal: null
    output: ,,
    pid: 50564
    stdout: null
    stderr: null
Stack:
Error: Command failed: gulp --gulpfile ./src/plugins/editing/gulpfile.js default
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Gulp.<anonymous> (/data/g3w-client/gulpfile.js:369:7)
    at module.exports (/data/g3w-client/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/data/g3w-client/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/data/g3w-client/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/data/g3w-client/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/data/g3w-client/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/data/g3w-client/node_modules/run-sequence/index.js:75:5)

**Comment by mohammed21986** [comment]
Get it above error after correcting the first one like u suggested to manually clone it.

**Comment by mohammed21986** [comment]
After solving first error, now getting below error.

```
root@ip-XX-XX-XX-XX:/data/g3w-client# npm run dev
```

```log
g3w-client@3.9.8 dev
gulp dev

[G3W-CLIENT] environment: development
[G3W-CLIENT] output folder: ../g3w-suite-docker/config/g3w-suite/overrides

[13:15:02] Using gulpfile /data/g3w-client/gulpfile.js
[13:15:02] Starting 'dev'...
[13:15:02] Starting 'clean:overrides'...
[13:15:02] Finished 'clean:overrides' after 3.02 ms
[13:15:02] Starting 'clone:default_plugins'...


### Cloning default plugins ###

[13:15:02] No gulpfile found
[13:15:02] 'clone:default_plugins' errored after 139 ms
[13:15:02] Error: Command failed: gulp --gulpfile ./src/plugins/editing/gulpfile.js default
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Gulp.<anonymous> (/data/g3w-client/gulpfile.js:369:7)
    at module.exports (/data/g3w-client/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/data/g3w-client/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/data/g3w-client/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/data/g3w-client/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/data/g3w-client/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/data/g3w-client/node_modules/run-sequence/index.js:75:5)
[13:15:02] 'dev' errored after 146 ms
[13:15:02] Error in plugin 'run-sequence(clone:default_plugins)'
Message:
    Command failed: gulp --gulpfile ./src/plugins/editing/gulpfile.js default
Details:
    status: 1
    signal: null
    output: ,,
    pid: 54456
    stdout: null
    stderr: null
Stack:
Error: Command failed: gulp --gulpfile ./src/plugins/editing/gulpfile.js default
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Gulp.<anonymous> (/data/g3w-client/gulpfile.js:369:7)
    at module.exports (/data/g3w-client/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/data/g3w-client/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/data/g3w-client/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/data/g3w-client/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/data/g3w-client/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/data/g3w-client/node_modules/run-sequence/index.js:75:5)
```

**Comment by mohammed21986** [comment]
below file is not present at this directory

```
./src/plugins/editing/gulpfile.js
```

**Comment by Raruto** [comment]
> ### Environment
> g3w-admin: 3.7

You are probably on [dev](https://github.com/g3w-suite/g3w-client-plugin-editing/tree/dev) branch, this should be the branch compatible with your environment: [g3w-client-plugin-editing@v3.7.8](https://github.com/g3w-suite/g3w-client-plugin-editing/tree/v3.7.8).

The same will also apply to the other default plugins ([openrouteservice](https://github.com/g3w-suite/g3w-client-plugin-openrouteservice/tree/v3.7.1), [qplotly](https://github.com/g3w-suite/g3w-client-plugin-qplotly/tree/v3.7.1), [qtimeseries](https://github.com/g3w-suite/g3w-client-plugin-qtimeseries/tree/v3.7.1)), you need to checkout for latest **v3.7.x** tag.

**Comment by mohammed21986** [comment]
Hi @Raruto 

after fixing the plugging issue, i'm trying to make client up by given procedure in the document, `npm run dev` but getting below error:

```sh
root@ip-x-x-x-x:/data/g3w-client# npm run dev
```

```log
g3w-client@3.8.17 dev
gulp dev --max-old-space-size=2048

[G3W-CLIENT] environment: development
[G3W-CLIENT] output folder: ../g3w-suite-docker/config/g3w-suite/overrides

[11:46:39] Using gulpfile /data/g3w-client/gulpfile.js
[11:46:39] Starting 'dev'...
[11:46:39] Starting 'clean:overrides'...
[11:46:39] Finished 'clean:overrides' after 21 ms
[11:46:39] Starting 'clone:default_plugins'...


### Cloning default plugins ###

[11:46:39] Finished 'clone:default_plugins' after 259 μs
[11:46:39] Starting 'build:dev_plugins'...


### Building plugin: ./src/plugins/editing/plugin.js ###

[11:46:39] Working directory changed to /data/g3w-client/src/plugins/editing
[11:46:39] Using gulpfile /data/g3w-client/src/plugins/editing/gulpfile.js
[11:46:39] Starting 'production'...
[11:46:39] Finished 'production' after 36 μs
[11:46:39] Starting 'browserify'...
[11:46:42] PluginError
    at new JS_Parse_Error (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at expect_token (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2110:9)
    at expect (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:36)
    at function_ (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2384:9)
    at expr_atom (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2622:24)
    at maybe_unary (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24) {
  message: '/data/g3w-client/src/plugins/editing/build.js: SyntaxError: Unexpected token operator «*», expected punc «(»',
  fileName: '/data/g3w-client/src/plugins/editing/build.js',
  lineNumber: 9695,
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify'
}


### Building plugin: ./src/plugins/openrouteservice/plugin.js ###

[11:46:42] Working directory changed to /data/g3w-client/src/plugins/openrouteservice
[11:46:42] Using gulpfile /data/g3w-client/src/plugins/openrouteservice/gulpfile.js
[11:46:42] Starting 'production'...
[11:46:42] Finished 'production' after 37 μs
[11:46:42] Starting 'browserify'...
[11:46:43] PluginError
    at new JS_Parse_Error (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at expect_token (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2110:9)
    at expect (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:36)
    at function_ (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2384:9)
    at expr_atom (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2622:24)
    at maybe_unary (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24) {
  message: '/data/g3w-client/src/plugins/openrouteservice/build.js: SyntaxError: Unexpected token operator «*», expected punc «(»',
  fileName: '/data/g3w-client/src/plugins/openrouteservice/build.js',
  lineNumber: 9176,
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify'
}


### Building plugin: ./src/plugins/qplotly/plugin.js ###

[11:46:43] Working directory changed to /data/g3w-client/src/plugins/qplotly
[11:46:44] Using gulpfile /data/g3w-client/src/plugins/qplotly/gulpfile.js
[11:46:44] Starting 'production'...
[11:46:44] Finished 'production' after 35 μs
[11:46:44] Starting 'browserify'...
[11:46:45] PluginError
    at new JS_Parse_Error (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at expect_token (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2110:9)
    at expect (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:36)
    at function_ (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2384:9)
    at expr_atom (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2622:24)
    at maybe_unary (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24) {
  message: '/data/g3w-client/src/plugins/qplotly/build.js: SyntaxError: Unexpected token operator «*», expected punc «(»',
  fileName: '/data/g3w-client/src/plugins/qplotly/build.js',
  lineNumber: 9003,
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify'
}


### Building plugin: ./src/plugins/qtimeseries/plugin.js ###

[11:46:45] Working directory changed to /data/g3w-client/src/plugins/qtimeseries
[11:46:45] Using gulpfile /data/g3w-client/src/plugins/qtimeseries/gulpfile.js
[11:46:45] Starting 'production'...
[11:46:45] Finished 'production' after 38 μs
[11:46:45] Starting 'browserify'...
[11:46:46] PluginError
    at new JS_Parse_Error (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at expect_token (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2110:9)
    at expect (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:36)
    at function_ (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2384:9)
    at expr_atom (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2622:24)
    at maybe_unary (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/data/g3w-client/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24) {
  message: '/data/g3w-client/src/plugins/qtimeseries/build.js: SyntaxError: Unexpected token operator «*», expected punc «(»',
  fileName: '/data/g3w-client/src/plugins/qtimeseries/build.js',
  lineNumber: 9120,
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify'
}
[11:46:46] Finished 'build:dev_plugins' after 6.84 s
[11:46:46] Starting 'browserify:app'...
[11:46:46] Starting 'concatenate:vendor_js'...
[11:46:46] Starting 'concatenate:vendor_css'...
[11:46:46] Starting 'fonts'...
[11:46:46] Starting 'images'...
[11:46:46] Starting 'datatable-images'...
[11:46:46] Starting 'html'...
[11:46:46] Finished 'html' after 75 ms
[11:46:47] Finished 'datatable-images' after 714 ms
[11:46:47] Finished 'concatenate:vendor_css' after 753 ms
[11:46:50] Finished 'images' after 4.51 s
[11:46:50] Finished 'concatenate:vendor_js' after 4.68 s
[11:46:52] Finished 'fonts' after 6.45 s
[11:46:52] Starting 'less'...
[11:46:54] Finished 'less' after 1.61 s
[11:46:59] Finished 'browserify:app' after 13 s
[11:46:59] Starting 'build:client'...
[11:46:59] Finished 'build:client' after 20 μs
[11:46:59] Starting 'browser-sync'...
[11:47:00] Finished 'browser-sync' after 324 ms
[11:47:00] Finished 'dev' after 21 s
[Browsersync] Proxying: http://127.0.0.1:8000
[Browsersync] Access URLs:
 -----------------------------------
       Local: http://localhost:3000/
    External: http://X.X.X.X:3000/
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 -----------------------------------
```

**Comment by Raruto** [comment]
> SyntaxError: Unexpected token operator «*», expected punc «(»',

Ref: https://github.com/g3w-suite/g3w-client/pull/365, you are probably still running incompatible plugin versions.

In any case, I advise you to wait a few more days until latest stable **g3w-suite@v3.8** comes out (some modern code, cleaner graphics, ...).

👋 Raruto

**Comment by mohammed21986** [comment]
Hi @Raruto, looks like now plugging issue is fixed.

```sh
root@ip-X-X-X-X:/data/g3w-client# npm run dev
```

```sh
g3w-client@3.7.19 dev
gulp dev --max-old-space-size=2048

[15:43:37] Using gulpfile /data/g3w-client/gulpfile.js
[15:43:37] Starting 'dev'...
[15:43:37] Starting 'build_external_assets'...
[15:43:37] Finished 'build_external_assets' after 22 ms
[15:43:37] Starting 'clean:dist'...
[15:43:37] Finished 'clean:dist' after 1.49 ms
[15:43:37] Starting 'browserify:app'...
[15:43:46] Finished 'browserify:app' after 8.91 s
[15:43:46] Starting 'fonts'...
[15:43:46] Starting 'images'...
[15:43:46] Starting 'datatable-images'...
[15:43:46] Finished 'datatable-images' after 37 ms
[15:43:46] Finished 'fonts' after 50 ms
[15:43:46] Starting 'less'...
[15:43:46] Finished 'images' after 401 ms
[15:43:46] Finished 'less' after 354 ms
[15:43:46] Starting 'assets'...
[15:43:46] Finished 'assets' after 26 μs
[15:43:46] Starting 'plugins'...
[15:43:46] Finished 'plugins' after 943 μs
[15:43:46] Starting 'watch'...
[15:43:46] Finished 'watch' after 435 ms
[15:43:46] Starting 'browser-sync'...
[15:43:46] Finished 'browser-sync' after 18 ms
[15:43:46] Finished 'dev' after 9.79 s
[Browsersync] Access URLs:
 -----------------------------------
       Local: http://localhost:3000/
    External: http://XX.X.X.XX:3000/
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 -----------------------------------
[Browsersync] Serving files from: src
[Browsersync] Serving files from: .

[15:46:23] Error: connect ECONNREFUSED 127.0.0.1:8000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8000
}
```
While trying to access web application on port 8000 then getting above error and with 3000 port getting below error, can you please guide me further.

![WhatsApp Image 2024-06-18 at 21 18 06_9a8bbc47](https://github.com/g3w-suite/g3w-client/assets/63414880/4c81d5bf-7d16-45b9-8efd-56b89b736a3b)
